// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC0WdzFw-Ip1tpXKJpHlY2oIEFdN6N5Uc',
    appId: '1:700574974620:web:fe92e0df4f0b1f2f42a359',
    messagingSenderId: '700574974620',
    projectId: 'senior-project-eb3b8',
    authDomain: 'senior-project-eb3b8.firebaseapp.com',
    databaseURL: 'https://senior-project-eb3b8-default-rtdb.firebaseio.com',
    storageBucket: 'senior-project-eb3b8.appspot.com',
    measurementId: 'G-S70VCCXXRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMWnMFp5zY9x1g3ymEegn7Cx-8Yg9tSXA',
    appId: '1:700574974620:android:c09b6579ccee9ada42a359',
    messagingSenderId: '700574974620',
    projectId: 'senior-project-eb3b8',
    databaseURL: 'https://senior-project-eb3b8-default-rtdb.firebaseio.com',
    storageBucket: 'senior-project-eb3b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATdIzVjqEqS7MWcUyN8UVHZUd3ZAnjEao',
    appId: '1:700574974620:ios:555fae501f898e8542a359',
    messagingSenderId: '700574974620',
    projectId: 'senior-project-eb3b8',
    databaseURL: 'https://senior-project-eb3b8-default-rtdb.firebaseio.com',
    storageBucket: 'senior-project-eb3b8.appspot.com',
    iosBundleId: 'com.example.socialWorkoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATdIzVjqEqS7MWcUyN8UVHZUd3ZAnjEao',
    appId: '1:700574974620:ios:290ab98bd192d19342a359',
    messagingSenderId: '700574974620',
    projectId: 'senior-project-eb3b8',
    databaseURL: 'https://senior-project-eb3b8-default-rtdb.firebaseio.com',
    storageBucket: 'senior-project-eb3b8.appspot.com',
    iosBundleId: 'com.example.socialWorkoutApp.RunnerTests',
  );
}
